#!/usr/bin/env php

<?php

use Poker\FriendGame;
use Poker\RandomGame;
use Poker\Kernel\HandHandler;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$hand = ['AS', 'TS', 'JH', 'QD', 'KC'];
(HandHandler::getIns()->getRanksByHand($hand));

$app = new Application('♥ php poker game ♥', '1.0');

$app->add(new RandomGame);
$app->add(new FriendGame);

$app->run();
